language: rust

sudo: false
dist: trusty


cache: cargo
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - export RUST_BACKTRACE=1
  - export PROXER_API_KEY=DUMMY
  - which rustfmt || cargo install rustfmt


script:
  - cargo update
  - cargo build
  - cargo test


rust:
  - stable
  - nightly

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
