language: rust
cache: cargo
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt


script:
  - cargo update
  - cargo build
  - cargo test


rust:
  - stable
  - nightly

env:
  - RUST_BACKTRACE=1
  - PROXER_API_KEY=DUMMY


notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
