[package]
name = "proxer"
version = "0.1.0"
authors = ["Paul Maruhn <paulmaruhn@gmail.com>"]

[dependencies]
serde_json = "1.0.2"
tokio-core = "0.1.8"
futures = "0.1.14"
log = "0.3.8"
reqwest = "0.6.2"
hyper = "0.11.1"
